// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  events_slice: dynamic(() => import("./EventsSlice")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  how_it_works: dynamic(() => import("./HowItWorks")),
};
